replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: host.example 
      paths:
      -  /
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
